# fly.toml app configuration file generated for pihenr on 2023-08-01T17:40:55-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pihenr"
primary_region = "scl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
